import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
// import React from "react"
// import { signIn, signOut, useSession } from 'next-auth/react'
import React, { useEffect } from 'react';
import { useSession, signIn } from 'next-auth/react';

export default function Home() {
  const { data: session, status } = useSession();
  useEffect(() => {
    if (status === 'unauthenticated') signIn();
  }, [status]);

  if (status !== 'authenticated') {
    return <h2>Loading...</h2>;
  }

  return (
    <>
      <div>
        <br/>
        <h1>{session.user.name},</h1>
        <h3> Welcome To Dashboard!</h3>
        <Link href="/about">
          <a>React Hook Form Library Try</a>
        </Link>
        </div>
    </>
  );
}
  // const { data: session, status } = useSession()
  // const loading = status === "loading"
  // if (loading) {
  //   return <p>Loading...</p>
  // }
  // return (
  //   <>

  //     {!session && (
  //       <>
  //         Not signed in <br />
  //         <button onClick={signIn}>Sign in</button>
  //       </>
  //     )}
  //     {session && (
  //       <>
  //         Signed in as {session.user.name} <br />
  //         <button onClick={signOut}>Sign out</button>
  //         <Link href="/private">
  //         <a>Go to private page</a>
  //       </Link>
  //       </>
  //     )}

  //       <Link href="/private">
  //         <a>Go to private page</a>
  //       </Link>
  //   </>
  // )
  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>done</title>
  //       <meta name="description" content="Generated by create next app" />
  //       {/* <link rel="icon" href="/favicon.ico" /> */}
  //     </Head>

  //     <h1>Home</h1>
  //     <Link href='/posts'>
  //       <a>getserversideprops</a>
  //     </Link><br />
  //     <Link href='/api/auth/signin'>
  //       <a>GITHUB_Signin</a>
  //     </Link>
      
  // <Container>
  //       <Row>
  //         <Col lg="6">

  //         </Col>
  //         <Col lg="6">
  //         </Col>
  //       </Row>

  //     </Container>
  //   </div>
  // )
// }
